; QUAD-UAV - firmware may bay: ESP32 (IMU/GPS/RF/DShot) + STM32F103 (PID)
[platformio]
default_envs = esp32_drone

[env:esp32_drone]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3
lib_deps =
    sparkfun/SparkFun BNO08x Cortex Based IMU@^1.0.0
    https://github.com/derdoktor667/DShotRMT.git#oldAPI
    mikalhart/TinyGPSPlus@^1.1.0
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit SSD1306@^2.5.15
extra_scripts =
    pre:dshot_patch.py
build_src_filter =
    +<*>
    -<main_stm32f103c8t6.cpp>
    -<Web/>
    -<Flight/>
    -<Flight.cpp>
    -<Flight.h>
    -<RF_RX/>

[env:stm32_drone]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
lib_deps =
    nrf24/RF24@^1.4.8
    stm32duino/STM32duino FreeRTOS@^10.3.2
build_src_filter =
    +<*>
    -<main_esp32.cpp>
    -<IMU/>
    -<Web/>
    -<GPS/>
